name: lorescue

description: "A new Flutter project."

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_blue_plus: ^1.35.3
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.0.0
  flutter_polyline_points: ^2.1.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  latlong2: ^0.9.1
  location: ^8.0.0
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  web_socket_channel: ^3.0.2
  flutter_map_mbtiles: ^1.0.4
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/verification_icon.png
